version: '3.9'

services:

  project-db:
    container_name: project-db
    platform: linux/amd64
    image: postgres:15.2-alpine
    ports:
      - "54322:5432"
    restart: always
    env_file: './pgsql/local/.env.local'
    volumes:
      - project-pgsql-data:/var/lib/postgresql/data
    networks:
      - project-net

  project-backend:
    container_name: project-backend
    build:
      context: ./backend
      args:
        - DEV=true
    image: project-app:latest
    tty: true
    ports:
      - "8000:8000"
    restart: unless-stopped
    working_dir: /app
    env_file: './backend/.env.local'
    environment:
      CONTAINER_ROLE: app
      CONTAINER_ENV: local
    volumes:
      - ./backend:/app
    depends_on:
      - project-db
    networks:
      - project-net

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - els-data:/var/lib/els/data
    networks:
      - project-net

volumes:
  project-pgsql-data:
  els-data:

networks:
  project-net:
    driver: bridge


