# Generated by Django 4.1.6 on 2023-11-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0002_alter_car_carrying_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="carrying_capacity",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
