# Generated by Django 4.1.6 on 2023-11-22 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleProxyModel",
            fields=[],
            options={
                "verbose_name": "Seller user",
                "verbose_name_plural": "Seller users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
        ),
    ]
